# Generated by Django 4.2.11 on 2024-12-24 21:13

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quote_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('quote_description', models.CharField(choices=[('1', '1 rutina a la setmana amb un preu de 15€ al mes'), ('3', '3 rutines a la setmana amb un preu de 30€ al mes'), ('0', 'Rutines ilimitades amb un preu de 50€ al mes')], default='1', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotes',
            },
        ),
        migrations.CreateModel(
            name='Horari_Classes',
            fields=[
                ('horari_classes_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('horari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horari_classes', to='trainer_app.horari')),
                ('usuari_inscrit', models.ManyToManyField(related_name='usuari_inscrit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'horari_classes',
            },
        ),
    ]
