# Generated by Django 4.2.11 on 2024-12-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horari_classes',
            old_name='horari_classes_id',
            new_name='_id',
        ),
    ]
