# Generated by Django 4.2.11 on 2024-11-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_rutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='dia',
            field=models.CharField(choices=[('Dilluns', 'Dilluns'), ('Dimarts', 'Dimarts'), ('Dimecres', 'Dimecres'), ('Dijous', 'Dijous'), ('Divendres', 'Divendres'), ('Dissabte', 'Dissabte'), ('Diumenge', 'Diumenge')], default='', max_length=10),
        ),
    ]
