# Generated by Django 4.2.11 on 2024-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_rutina_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='horari',
        ),
        migrations.AddField(
            model_name='rutina',
            name='hora',
            field=models.CharField(choices=[('16:00', '16:00 - 17:00'), ('17:00', '17:00 - 18:00'), ('18:00', '18:00 - 19:00'), ('19:00', '19:00 - 20:00'), ('20:00', '20:00 - 21:00')], default="'16:00 - 17:00'", max_length=5),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='dia',
            field=models.CharField(choices=[('Dilluns', 'Dilluns'), ('Dimarts', 'Dimarts'), ('Dimecres', 'Dimecres'), ('Dijous', 'Dijous'), ('Divendres', 'Divendres'), ('Dissabte', 'Dissabte'), ('Diumenge', 'Diumenge')], default='Dilluns', max_length=10),
        ),
    ]
