# Generated by Django 4.2.11 on 2024-12-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0006_remove_rutina_horari_rutina_hora_alter_rutina_dia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rutina',
        ),
    ]
