# Generated by Django 4.2.11 on 2024-11-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_alter_rutina_durada_alter_rutina_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='hora',
            field=models.CharField(choices=[('16:00', '16:00 '), ('17:00', '17:00 '), ('18:00', '18:00 '), ('19:00', '19:00 '), ('20:00', '20:00 ')], default='16:00', max_length=5),
        ),
    ]
