# Generated by Django 4.2.11 on 2024-11-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0011_alter_rutina_durada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='dia',
            field=models.CharField(choices=[('Dilluns', 'Dilluns'), ('Dimarts', 'Dimarts'), ('Dimecres', 'Dimecres'), ('Dijous', 'Dijous'), ('Divendres', 'Divendres')], default='Dilluns', max_length=10),
        ),
    ]
