# Generated by Django 4.2.11 on 2024-11-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0012_alter_rutina_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='durada',
        ),
    ]
