# Generated by Django 4.2.11 on 2024-12-01 16:20

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0013_remove_rutina_durada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='id',
        ),
        migrations.AddField(
            model_name='rutina',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutina',
            name='rutina_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='recomenacions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Horari',
            fields=[
                ('horari_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Dilluns', 'Dilluns'), ('Dimarts', 'Dimarts'), ('Dimecres', 'Dimecres'), ('Dijous', 'Dijous'), ('Divendres', 'Divendres')], default='Dilluns', max_length=10)),
                ('hora', models.CharField(choices=[('16:00', '16:00 '), ('17:00', '17:00 '), ('18:00', '18:00 '), ('19:00', '19:00 '), ('20:00', '20:00 ')], default='16:00', max_length=5)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaris', to='gym_app.rutina')),
            ],
            options={
                'db_table': 'horaris',
            },
        ),
    ]
