# Generated by Django 4.2.11 on 2024-12-01 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0014_remove_rutina_dia_remove_rutina_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutines', to=settings.AUTH_USER_MODEL),
        ),
    ]
