# Generated by Django 4.2.11 on 2024-12-12 18:24

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('rutina_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.CharField(max_length=100)),
                ('exercicis', models.TextField()),
                ('recomenacions', models.TextField(blank=True, null=True)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rutines',
            },
        ),
        migrations.CreateModel(
            name='Horari',
            fields=[
                ('horari_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Dilluns', 'Dilluns'), ('Dimarts', 'Dimarts'), ('Dimecres', 'Dimecres'), ('Dijous', 'Dijous'), ('Divendres', 'Divendres')], default='Dilluns', max_length=10)),
                ('hora', models.CharField(choices=[('16:00', '16:00 '), ('17:00', '17:00 '), ('18:00', '18:00 '), ('19:00', '19:00 '), ('20:00', '20:00 ')], default='16:00', max_length=5)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaris', to='trainer_app.rutina')),
            ],
            options={
                'db_table': 'horaris',
            },
        ),
    ]
